service: aws-AS
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-east-1:035370785641:table/TaskTable 
      
functions:
  hello:
    handler: src/hello.hello
    events:
      - httpApi:
          path: /
          method: get

  createTask:
    handler: src/addTask.addTask
    events:
      - httpApi:
          path: /tasks
          method: post
  
  getTask:
    handler: src/getTask.getTask
    events:
      - httpApi:
          path: /tasks
          method: get

  getTaskiD:
    handler: src/getTaskId.getTaskId
    events:
      - httpApi:
          path: /tasks/{id}
          method: get


resources: 
  Resources:
    TaskTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TaskTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
       